### ISSUE TITLE
talk with DimensionDataResearch/octopus

### ISSUE THREAD

**Issue by mbainter** [terra-farm/meta#13]
https://github.com/DimensionDataResearch/terraform-octopus

**Comment by josephholsten** [comment]
@mbainter are you using this? I see there hasn't been a commit in almost a year, but it's not behind on PRs or issues. What would you like to see changed?

**Comment by mbainter** [comment]
I am about to, and saw that there hadn't been a commit in almost a year, while octopus continues to be actively developed and improved - esp the API. I don't yet have a need, but I figured I'd be running into them sooner rather than later and thought I'd get it on the list in advance of having contributions to make.

I may have mis-understood your intent, but I figured it would be worth reaching out to the current folks to ask them about if they'd be interested in participating in this effort with their work.

**Comment by josephholsten** [comment]
@mbainter absolutely! At this point, this org/repo is more about communication than anything else.

With sous chefs, we try not to adopt a project unless someone is willing to be the primary maintainer: essentially that they'll try to stay on top of tickets and coordinate any other contributors. Are you up for that? If not, we should see if any of the folks following the provider repo are.

**Comment by mbainter** [comment]
I'm really hoping that they're still interested in maintaining it, but would be interested in a project like this one that could provide community ownership.  While I'm interested in contributing, I don't think I have the skill or experience in Go yet to take on being the primary - so if they're *not* interested this might have to wait.

**Comment by josephholsten** [comment]
FYI: https://github.com/terraform-providers

**Comment by josephholsten** [comment]
cf https://github.com/DimensionDataResearch/terraform-octopus/issues/1

**Comment by josephholsten** [comment]
@mbainter please keep me up to date on this, if someone's using unmaintained code that's very useful ammo to have.

**Comment by tintoy** [comment]
TBH I didn't think anyone was really using this, but I'd love for it to be carried forward (still happy to help out, too). Count me in :)

**Comment by tintoy** [comment]
Bump - any movement on this?

**Comment by josephholsten** [comment]
ok, I've given @tintoy access to transfer the provider here.

@mbainter what do we need to set up acceptance tests?

**Comment by tintoy** [comment]
Moved to https://github.com/terra-farm/terraform-octopus 😄

As for acceptance tests, I guess we'd need an Octopus server; it's the sort of thing we can set up for each run with Octopus and maybe Chef / Ansible?

**Comment by josephholsten** [comment]
@mbainter acc test convo has moved to https://github.com/terra-farm/terraform-octopus/issues/3
