### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by rowleyaj** [terra-farm/meta#14]
This isn't necessarily related to terra-farm more terraform in general, but since this repo says we're discussing things in the main terraform room on Gitter I thought I'd bring this up here to seek opinion.

I mistakenly joined the wrong room initially. It looks like terraform has two rooms on gitter, one created alongside the github repo, and one created as a separate community.

https://gitter.im/hashicorp/terraform - 94 people
https://gitter.im/hashicorp-terraform/Lobby - 1623 people

Looking at nomad and consul it seems they don't have this split and have their own communities:
https://gitter.im/hashicorp-nomad
https://gitter.im/hashicorp-consul

Reading https://gitter.zendesk.com/hc/en-us/articles/200178951-Gitter-communities-and-rooms the HashiCorp org admins should have admin on the Gitter community called HashiCorp. Is it worth approaching someone from HashiCorp and suggesting they create rooms for each of the repos and direct them to the other community channels?

**Comment by jakauppila** [comment]
How does everyone feel about Gitter? Maybe it's just my experience, but I feel like it tends to be a bit too cluttered and questions/conversations get lost pretty quickly compared to Slack.

It could just be the nature of the questions I've asked, time of day, or just the willingness of the people lurking on there to answer, but it hasn't been nearly as nice an experience of say, the Chef Community Slack group.

**Comment by ringods** [comment]
Can we also stay away from Slack? In the free version, there is a very limited history too. Also, this week they decided to drop support for the XMPP and IRC gateways. If we are an open community, why use a closed tool?

Source: https://news.ycombinator.com/item?id=16539857

@rowleyaj as an organizer of the Belgium Hashicorp User Group, I might be able to contact someone within Hashicorp for the Gitter access.

**Comment by ringods** [comment]
@rowleyaj @josephholsten @jakauppila may I suggest to take a look at [Discord](https://discordapp.com/)?

Some OpenSource communities are switching to it, coming from Slack:
* [Concourse CI](https://discuss.concourse-ci.org/t/join-us-in-discord/34)
* [React.JS](https://reactjs.org/blog/2015/10/19/reactiflux-is-moving-to-discord.html)

Advantage already found: you only need a single account to join all possible communities. ;-)

**Comment by rowleyaj** [comment]
Interesting reads there @ringods, thanks for the links. I think Discord suffers from the same concerns as Slack though - it's closed isn't it?

Although Gitter has it's problems, I think the user counts there are important to consider - now 3248 in hashicorp-terraform community lobby, and  277 on hashicorp/terraform.

I think our best option for terra-farm communication would be to request a terra-farm room under the hashicorp-terraform community. An alternative would be to create our own community there / use the repo one. I prefer the first option as we're not really a new community, more a part of the terraform community - similar to the sous-chefs channel in the chef-community Slack.

@ringods since you offered please could you reach out to Hashicorp if that's still ok?

**Comment by ringods** [comment]
@rowleyaj I have reached out to my point of contact within Hashicorp and pointed them to this conversation. I'll follow up on email replies, but hope they join in on the conversation here directly.

**Comment by ringods** [comment]
@rowleyaj @josephholsten I have sent out an email, followed by a reminder to my contact at Hashicorp but got no reply.

I would suggest to go forward on our own: create a Gitter community `gitter.im/terra-farm` and create rooms related to the provider and/or modules:

* `meta` - room for managing the organization, website, etc.
* `virtualbox` - room for virtualbox provider
* `octopus` - room for octopus provider
* `aws` - room for AWS targeted modules
* ...

**Comment by ringods** [comment]
@rowleyaj @josephholsten I got a response from Hashicorp and they are discussing it internally. We might get our room in the `hashicorp-terraform` community... Hang tight.

**Comment by rowleyaj** [comment]
Look forward to hearing more @ringods!

**Comment by ringods** [comment]
We have our room! 🎉 

https://gitter.im/hashicorp-terraform/terra-farm
