### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by ringods** [terra-farm/meta#16]
We have to start promoting this initiative. I did my share yesterday. 

* [Tweet](https://twitter.com/ringods/status/979085794542571520)
* Presentation at Belgium Hashicorp User Group meetup. See the last slides of [my presentation](https://www.slideshare.net/ringods/terraform-provider-development).

😃 

Other ideas:
* main website on Github pages: https://terra-farm.github.io
* Each provider or module can be published [as a subfolder](https://help.github.com/articles/user-organization-and-project-pages/), e.g. for `terraform-provider-virtualbox` that would be https://terra-farm.github.io/terraform-provider-virtualbox

**Comment by ringods** [comment]
@josephholsten I would like to bootstrap a Github pages website for terra-farm. Could you rename this repository:

https://github.com/terra-farm/terraform-github-org

to

https://github.com/terra-farm/terra-farm.github.io

which is the name it should be according the (Github Pages documentation](
https://help.github.com/articles/user-organization-and-project-pages/#user-and-organization-pages-sites)

Then add me as an admin on that repo please.

**Comment by josephholsten** [comment]
I've created a new repo at https://github.com/terra-farm/terra-farm.github.io, please let me know if you need more permissions than I've set up. Thanks so much for taking on this work!

The original point of terraform-github-org was to manage membership, as sous-chefs does at https://github.com/sous-chefs/terraform-github-org, so I've left it alone for us to use at a later date.

**Comment by ringods** [comment]
@josephholsten tnx. Didn't know that it was the intent to terraform the setup of this github org. I'll help out to that initiative too. 😄

**Comment by rowleyaj** [comment]
I see everyone was busy working away whilst we were enjoying our long weekend due to the bank holidays in the UK. 😉 

@ringods thanks for taking this on. What did you have in mind for the website? I think @damacus did the sous-chefs one using Hugo?

**Comment by ringods** [comment]
@rowleyaj I also had Hugo in mind as it is a very powerful, yet easy tool to use. I just don't know which theme to use. Do we have a web designer in our ranks in case we want to have our own branding? :-)

One thing I found out just before the weekend is that Github pages for user or organization sites should have the bare site content in the `master` branch. For project pages, you can use the `gh-pages` branch which means you can use master to have the pre-build site content.

I'm gonna give it a whirl to see if we can use a reverse approach for the organization site: e.g. build from a detached `site-sources` branch and push the result onto the `master` branch.

**Comment by damacus** [comment]
Happy to Hugo. 

Checkout https://github.com/sous-chefs/website if you want some ideas.

**Comment by ringods** [comment]
@rowleyaj @josephholsten  I created the `master` branch and an orphan `site` branch in the website repo. The `site` branch will contain the Hugo source files and after building, the content will be pushed onto `master`. I have provided a minimal `index.html` file manually for the moment. I have also set the `site` branch as the default branch on Github.

Although nothing to be seen yet, our site *is* live. 😆 

https://terra-farm.github.io

**Comment by josephholsten** [comment]
Ok, so we’ve got the basic site, anyone know what’s needed to have the provider-specific stuff? Shall we get virtualbox set up first?

**Comment by ringods** [comment]
@josephholsten there are 2 big options:

* we build the main site *and* all the providers and/or module docs in one go. In this case, we can choose the URL name, e.g. https://terra-farm.github.io/providers/virtualbox. The advantage is that the whole site will be very uniform and we can detect dead links at build time. The provider/module repos only have to provide content for the Hugo build process.
* we let every of the repositories build itself as a separate Github Pages project site. Each site will end up under the main site with the name of the repo as subfolder: https://terra-farm.github.io/terraform-provider-virtualbox. Since each site has to set up their website build, the consistency between main site and all the provider/module sites could be suboptimal.

Personally, I prefer to take the first route.

**Comment by josephholsten** [comment]
Well, I’m guessing it’s easiest to get /something/ quickly the first way, and we could switch to the other way later if we notice doc lagging behind providers. And we could always build toooling to scrape the doc out of the individual repos if we care that much.

**Comment by ringods** [comment]
@josephholsten @rowleyaj The Travis-CI build has been set up for the terra-farm website. I'm going to close this issue. Please file further requests for the website in the [terra-farm.github.io](https://github.com/terra-farm/terra-farm.github.io/issues) issues.
