### ISSUE TITLE
Organization ownership?

### ISSUE THREAD

**Issue by ringods** [terra-farm/meta#17]
Hello @josephholsten and @rowleyaj,

I would like to push things forward around `terra-farm`, but I have been blocked a few times now, waiting on one of you to approve or execute something. I would very much like to get some flow of work done.

Are you OK with accepting me as an organisation owner?

**Comment by rowleyaj** [comment]
@ringods no objections from myself. You've been doing some great work so far from what I've seen. I wouldn't want to stand in the way of progress!

**Comment by josephholsten** [comment]
@ringods Congratulations! Go forth and make things slightly less terrible!

**Comment by ringods** [comment]
@josephholsten thanks for the confidence in me. Did you also grant me the rights in the Github org? I haven't seen anything changing regarding my access to org or repos.

**Comment by rowleyaj** [comment]
@ringods changed your org role to owner.

I've also approved https://github.com/terra-farm/terraform-github-org/pull/1 which will be the basis for making these changes via code later.
