### ISSUE TITLE
Transfer of UltraDNS provider out of official Terraform setup

### ISSUE THREAD

**Issue by ringods** [terra-farm/meta#19]
I reached out to Hashicorp and asked for transfer of ownership of the UltraDNS provider codebase to this organization. 

User @aliasgharmhowwala [wants to maintain](https://github.com/terra-farm/udnssdk/pull/69#issuecomment-613367136) the provider and the [client sdk](https://github.com/terra-farm/udnssdk) (which is already under this organization).

**Comment by ringods** [comment]
@aliasgharmhowwala you should have received an email invitation to join the UltraDNS team on Github Terra-Farm organization. If you received an invitation twice, accept via the last mail received.

**Comment by ringods** [comment]
It seems I had to email Hashicorp directly for this transfer request. I did so today.

**Comment by ringods** [comment]
@aliasgharmhowwala it seems we were a few weeks late with this request. The provider maintenance has been taken up by Neustar (company)

https://github.com/terraform-providers/terraform-provider-ultradns

It's no longer unmaintained, but no transfer planned to the Terra-Farm organization.

**Comment by josephholsten** [comment]
Sorry for the confusion, @aliasgharmhowwala works at Neustar.
