### ISSUE TITLE
talk with btobolaski/linode

### ISSUE THREAD

**Issue by josephholsten** [terra-farm/meta#9]
https://github.com/btobolaski/terraform-provider-linode

**Comment by josephholsten** [comment]
cf https://github.com/btobolaski/terraform-provider-linode/issues/11

**Comment by displague** [comment]
I would be interested in having Linode added to core. The existing plugin started by btobolaski is basic and handles only Linodes. As a provider Linode offers DNS, Load balancing, Backups, and other features cooking in Terraform cloud providers.  Would Terraform accept a core module at this stage?  

I am a maintainer on the btoloboski repo and a Linode employee.  I've made some improvements over the previous PR but haven't opened a new one yet.  What differences are needed over the last PR to add Linode to core?

Linode is rolling out a new API very soon. It is possible that the plugin could be refactored to use a different API library with other dependency changes to take advantage of the new API.  I mention this incase dependency changes are a concern for core.

**Comment by codekoala** [comment]
I'd be interested in helping with this effort. Especially with the recently announced block storage beta program.

**Comment by josephholsten** [comment]
@displague @codekoala ok, then the next step is we need a primary maintainer who's willing to work through this process.

https://github.com/hashicorp/terraform/pull/3363 Was closed because no one was updating the PR. This should be easier since we won't have to fight with the rate of change for core, but we still need at least one person dedicated to this.

Are either of you interested? Do you have a commit bit on the provider repo? I can start reviewing it to see what changes need be made to get it in.

**Comment by displague** [comment]
I'm a newly dubbed maintainer and ready to get this going:
    * https://gist.github.com/displague/5497abe1c23e214cb27160d9faaa7883
    * https://github.com/displague/terraform/commits/add-linode-provider

**Comment by codekoala** [comment]
I don't currently have any permissions on the provider repo. I've never worked on a plugin for terraform, but I do have a couple of accepted PRs for azurerm.

**Comment by rowleyaj** [comment]
Closing this issue per comments on the linked issue at https://github.com/btobolaski/terraform-provider-linode/issues/11#issuecomment-371980109

**Comment by josephholsten** [comment]
@rowleyaj thanks!

**Comment by displague** [comment]
Just following up that you can now **Star** ⭐️ , *Watch* 👁 , and Fork 🍴 :
- https://github.com/terraform-providers/terraform-provider-linode
